version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - "5080:80"
      - "5443:443"
    volumes:
      - .:/app:cached
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./scripts/docker/:/tmp
      - mkcert-data:/etc/ssl/certs/
    command: "/tmp/wait-for-mkcert-certificate.sh"
    depends_on:
      - php
      - mkcert
    networks:
      default:
        aliases:
          - api.dev.hello-world.ovh

  php:
    build: .docker/php
    working_dir: /app
    volumes:
      - .:/app:cached
      - ./vendor:/app/vendor
    environment:
      APP_ENV: dev
    depends_on:
      - mysql
      - redis

  redis:
    image: "redis:alpine"

  mysql:
    ports:
      - "5306:3306"
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: www
      TZ: Europe/Paris
    volumes:
      - db_data:/var/lib/mysql
    depends_on:
      - "redis"

  mkcert:
    platform: linux/x86_64
    build: ./.docker/mkcert
    volumes:
      - ./scripts/docker/:/tmp
      - mkcert-data:/root/.local/share/mkcert
    environment:
      domain: api.dev.hello-world.ovh

volumes:
  db_data: ~
  mkcert-data: ~
