name: 🗳 2 - Merge release

on:
  pull_request:
    branches:
      - 'release**'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests (automerge-action)
        uses: pascalgn/automerge-action@v0.14.3
        env:
          MERGE_LABELS: "autorelease: pending"
          MERGE_DELETE_BRANCH: true
          MERGE_METHOD: merge
          MERGE_METHOD_LABELS: autorelease=merge
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
