on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'ci/**'
name: lint
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php --diff --dry-run
  Doctrine:
    name: Doctrine migration
    runs-on: ubuntu-latest
#    needs: php-cs-fixer
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
      - run: |
          php bin/console doctrine:schema:validate --skip-sync
